spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/reservation
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    #        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher