spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/Central
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



jwt:
  token:
    key:
      roles: role
      secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK

    expired_time: 3600000

logging:
  level:
    org:
      springframework:
        security:
          web:
            access:
              intercept:
                AuthorizationFilter=DEBUG:


encrypt:
  secretKey: "fhkljbewouin423adklj32nt38490b43"