server:
  port: 0

spring:
  application:
    name: security-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/RESERVATION
    username: root
    password:

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}



jwt:
  token:
    key:
      roles: role
      secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK

    expired_time: 3600000


encrypt:
  secretKey: "fhkljbewouin423adklj32nt38490b43"